// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xouqrbnibabiazvutzwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvdXFyYm5pYmFiaWF6dnV0end1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDI4MDgsImV4cCI6MjA2NTgxODgwOH0.JbF14WT1-aqQNqBkQI3deZ-YgOWlKAx-Jyw1wmTSA2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);